name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  pull_request:
    branches: ['develop']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: actions/setup-java@v3.10.0
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: publish
          build-root-directory: mrr
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
