name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  pull_request:
    branches: ['develop']
  push:
    branches: ['develop']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: actions/setup-java@v3.10.0
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish Package - lib-dex-commons
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: publish
          build-root-directory: local_libs/lib-dex-commons
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Package - lib-bumblebee
        run: mvn --batch-mode deploy --file local_libs/lib-bumblebee/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
