name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  pull_request:
    branches: ['develop']
  push:
    branches: ['develop']
    paths:
      - local_libs/**
      - .github/workflows/build-local-libs.yml
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: actions/setup-java@v3.10.0
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: >
            [
              {
                "id": "github",
                "name": "github data exchange hl7",
                "url": "https://maven.pkg.github.com/boris-ning-usds/data-exchange-hl7"
              },
              {
                "id": "github-hl7-pet",
                "name": "github cdcgov hl7-pet",
                "url": "https://maven.pkg.github.com/cdcgov/hl7-pet"
              }
            ]
          servers: >
            [
              {
                "id": "github",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              },
              {
                "id": "github-hl7-pet",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              }
            ]
      - name: Publish Package - lib-bumblebee
        run: mvn --batch-mode deploy --file local_libs/lib-bumblebee/pom.xml -Dmaven.test.skip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Package - lib-nist-validator
        run: mvn --batch-mode deploy --file local_libs/lib-nist-validator/pom.xml -Dmaven.test.skip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Package - lib-dex-commons
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: publish
          build-root-directory: local_libs/lib-dex-commons
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Package - lib-cloud-proxy
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: publish
          build-root-directory: local_libs/lib-cloud-proxy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
